# Generated by Django 5.1.7 on 2025-05-04 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Nome da Loja",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(18)],
                        verbose_name="CNPJ",
                    ),
                ),
                ("address", models.TextField(verbose_name="Endereço")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("suspended", "Suspensa"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="Tipo de Loja",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.05,
                        max_digits=5,
                        verbose_name="Taxa de Comissão",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Suporte Prioritário"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loja Parceira",
                "verbose_name_plural": "Lojas Parceiras",
                "ordering": ["-created_at"],
            },
        ),
    ]
