# Este arquivo define o pipeline de CI/CD para o projeto SuppliFIT.
# Ele é dividido em dois jobs principais: build-and-test e deploy.

# O job 'build-and-test' realiza as seguintes tarefas:
# - Configura os serviços necessários, como o banco de dados PostgreSQL.
# - Instala dependências do backend e frontend.
# - Executa testes automatizados para garantir a qualidade do código.

# O job 'deploy' realiza as seguintes tarefas:
# - Faz login no Docker Hub para publicar imagens Docker.
# - Constrói e publica as imagens Docker do backend e frontend.
# - Implanta os serviços localmente usando o Docker Compose.

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: supplifit
        ports:
          - 5432:5432

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Instalar dependências do backend
      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Executar testes do backend
      - name: Run backend tests
        working-directory: backend
        run: |
          source $(poetry env info --path)/bin/activate
          python manage.py test

      # Configurar Node.js para o frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependências do frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Executar testes do frontend
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e publicar imagens Docker
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      # Implantar no ambiente local
      - name: Deploy locally
        run: |
          docker-compose pull
          docker-compose up -d
